export const generosMusicais = [
    "Blues",
    "Canções Esquisitas",
    "Folk Japonês",
    "Hip-Hop",
    "Hits do Verão",
    "Jazz",
    "METAL",
    "Música Alternativa",
    "Música Ambiente",
    "Música Americana",
    "Música Assombrosa",
    "Música Barroca",
    "Música Clássica",
    "Música Eletrônica",
    "Música Latina",
    "Música Mundial",
    "Música New Age",
    "Música NuDisco",
    "Música Pop",
    "Música Pop Pré-adolescente",
    "Música Retrô",
    "Música Romântica",
    "Música S-Pop",
    "Música Soul",
    "Música da Ilha",
    "Música de Cabine de DJ",
    "Música de Concentração",
    "Música de Férias de Inverno",
    "Música de Quem Canta e Compõe",
    "Música de Quintal",
    "Pop Latino",
    "Rádio Infantil",
    "Rádio de Canções de Ninar"
  ];
  