export const generosMusicais = [
    "Blues",
    "Canções Esquisitas",
    "Folk Japonês",
    "Hip-Hop",
    "Hits do Verão",
    "Jazz",
    "METAL",
    "Música Alternativa",
    "Música Ambiente",
    "Música Americana",
    "Música Assombrosa",
    "Música Barroca",
    "Música Clássica",
    "Música Eletrônica",
    "Música Latina",
    "Música Mundial",
    "Música New Age",
    "Música NuDisco",
    "Música Pop",
    "Música Pop Pré-adolescente",
    "Música Retrô",
    "Música Romântica",
    "Música S-Pop",
    "Música Soul",
    "Música da Ilha",
    "Música de Cabine de DJ",
    "Música de Concentração",
    "Música de Férias de Inverno",
    "Música de Quem Canta e Compõe",
    "Música de Quintal",
    "Pop Latino",
    "Rádio Infantil",
    "Rádio de Canções de Ninar"
  ];
  
  export const caracteristicasDosSims = [
    "Amantes da Natureza",
    "Amantes dos Animais",
    "Decidem com o Coração",
    "Fãs de Romance",
    "Peraltas",
    "Sims Argumentativos",
    "Sims Caseiros",
    "Sims Egoístas",
    "Sims Energéticos",
    "Sims Engraçados",
    "Sims Entusiasmados",
    "Sims Esforçados",
    "Sims Familiares",
    "Sims Idealistas",
    "Sims Intelectuais",
    "Sims Otimistas",
    "Sims Pessimistas",
    "Sims Sem Ambição"
  ];
  
  export const topicosDeConversa = [
    "Comportamento Tolo",
    "Conversa Fiada",
    "Discussão de Interesses",
    "Discussão de Passatempos",
    "Discussões",
    "Elogios",
    "Fofocas",
    "Histórias",
    "Humor Escatológico",
    "Interações Maliciosas",
    "Intimidade Física",
    "Paquera",
    "Pensamentos Profundos",
    "Piadas",
    "Reclamações",
    "Tramoia",
    "Travessuras"
  ];
  
  export const atividades = [
    "Bem-estar",
    "Boliche",
    "Canto",
    "Ciência Aeroespacial",
    "Comédia",
    "Confeitaria",
    "Culinária",
    "Dança",
    "Escalada",
    "Escrita",
    "Esqui",
    "Fotografia",
    "Ginástica",
    "Interpretação",
    "Jardinagem",
    "Mecânica",
    "Mixagem de DJ",
    "Mixologia",
    "Pesca",
    "Pesquisa e Debate",
    "Piano",
    "Pintura",
    "Produção de Mídia",
    "Programação",
    "Robótica",
    "Snowboarding",
    "Travessura",
    "Videogame",
    "Violino",
    "Violão/Guitarra",
    "Órgão de Tubos"
  ];
  
  export const lModosDeVida = [
    "Ambiciosos na Carreira",
    "Artesanato",
    "Comprometidos",
    "Culinária",
    "Falidos",
    "Habilidade de Preparo de Bebidas",
    "Habilidades Acadêmicas",
    "Habilidades Interpessoais",
    "Habilidades da Natureza",
    "Habilidades de Apresentação",
    "Habilidades de Engenharia",
    "Habilidades de Mídia e Tecnologia",
    "Habilidades de Saúde e Esportes",
    "Habilidosos",
    "Profissionais Independentes",
    "Relaxados",
    "Ricos",
    "Senso de Humor"
  ];
  
  export const lCaracteristicas = [
    "Amantes da Natureza",
    "Amantes dos Animais",
    "Ambiciosos",
    "Argumentativos",
    "Bagunceiros",
    "Caseiros",
    "Decidem com o Coração",
    "Egoístas",
    "Energéticos",
    "Sims Engraçados",
    "Entusiasmados",
    "Esforçados",
    "Familiares",
    "Idealistas",
    "Intelectuais",
    "Limpos",
    "Otimistas",
    "Pessimistas",
    "Sem Ambição"
  ];

  export const lcoresDeCabelo = [
    "Cabelos Azul-escuros",
    "Cabelos Azul-turquesa",
    "Cabelos Brancos",
    "Cabelos Castanhos",
    "Cabelos Castanhos Dourados",
    "Cabelos Grisalhos",
    "Cabelos Laranja",
    "Cabelos Loiros",
    "Cabelos Platinados",
    "Cabelos Pretos",
    "Cabelos Rosa-choque",
    "Cabelos Roxo Pastel",
    "Cabelos Verdes",
    "Cabelos Vermelhos"
  ];
  
  